**Import all packages needed**

In [1]:
import pandas as pd
import numpy as np

Create all dataframe with 4 columns and 4 rows with features named  `'feature_1', 'feature_2', 'feature_3', 'feature_4'`

In [15]:
features = ['feature_1', 'feature_2', 'feature_3', 'feature_4']
data = np.random.randint(1, 100, size=(4, 4))
df = pd.DataFrame(data, columns=features)

df

   feature_1  feature_2  feature_3  feature_4
0         19         16         66          8
1         19         20         79          9
2         93         87         98         26
3         84         43         13         36

Rename the column Names to `'Random Value 1', 'Random Value 2', 'Random Value 3', 'Random Value 4'`

In [3]:
df.columns = [f'Random value {i + 1}' for i in range(len(features))]

df

   random value 1  random value 2  random value 3  random value 4
0              50              28              96              94
1              67              24              45              36
2              42               2              10              35
3              75              16              21              16

Descriptive Statistics

In [4]:
df.describe()

       random value 1  random value 2  random value 3  random value 4
count        4.000000         4.00000        4.000000        4.000000
mean        58.500000        17.50000       43.000000       45.250000
std         15.154757        11.47461       38.236109       33.777458
min         42.000000         2.00000       10.000000       16.000000
25%         48.000000        12.50000       18.250000       30.250000
50%         58.500000        20.00000       33.000000       35.500000
75%         69.000000        25.00000       57.750000       50.500000
max         75.000000        28.00000       96.000000       94.000000

Column Data types

In [5]:
df.dtypes

random value 1    int64
random value 2    int64
random value 3    int64
random value 4    int64
dtype: object

Checking for NULL values

In [6]:
df.isnull()

   random value 1  random value 2  random value 3  random value 4
0           False           False           False           False
1           False           False           False           False
2           False           False           False           False
3           False           False           False           False

Column Location method

In [11]:
df[['random value 2', 'random value 3']]

   random value 2  random value 3
0              28              96
1              24              45
2               2              10
3              16              21

Index Location Method

In [14]:
df.iloc[0:4, 1:3]

   random value 2  random value 3
0              28              96
1              24              45
2               2              10
3              16              21